/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.EncounterDirectory;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author arjun
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    PatientDirectory patientList;
    EncounterDirectory encounterList;
    public SearchJPanel(PatientDirectory patientList, EncounterDirectory encounterList) {
        initComponents();
        this.patientList = patientList;
        this.encounterList = encounterList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatientRecord = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchComboBox = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        txtSearchLow = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEncounter = new javax.swing.JTable();
        txtSearchHigh = new javax.swing.JTextField();

        tablePatientRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientId", "First Name", "Last Name", "Gender", "Age", "Community", "City", "Encounter Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatientRecord);
        if (tablePatientRecord.getColumnModel().getColumnCount() > 0) {
            tablePatientRecord.getColumnModel().getColumn(0).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(1).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(2).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(3).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(4).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(5).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(6).setResizable(false);
            tablePatientRecord.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 120, 0));
        jLabel1.setText("Search Records");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 143, 0));
        jLabel2.setText("Abnormal PatientList");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 143, 0));
        jLabel3.setText("Search by");

        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "City", "Community", "Age" }));
        searchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboBoxActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearchLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchLowActionPerformed(evt);
            }
        });

        tableEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Low BP", "High BP", "Heart Rate", "Weight", "Is Healthy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEncounter);
        if (tableEncounter.getColumnModel().getColumnCount() > 0) {
            tableEncounter.getColumnModel().getColumn(0).setResizable(false);
            tableEncounter.getColumnModel().getColumn(1).setResizable(false);
            tableEncounter.getColumnModel().getColumn(2).setResizable(false);
            tableEncounter.getColumnModel().getColumn(3).setResizable(false);
            tableEncounter.getColumnModel().getColumn(4).setResizable(false);
            tableEncounter.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(30, 30, 30)
                                                .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(btnSearch))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(txtSearchHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtSearchLow, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(330, 330, 330))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchLowActionPerformed

    private void DisplayPatientData(ArrayList<Patient> tempList){
        
        DefaultTableModel TableModelPatient = (DefaultTableModel) tableEncounter.getModel();
             TableModelPatient.setRowCount(0);
//             System.out.print(patientList.getPatientList().size());
             for(Patient patient : tempList){
            Object[] dummyRow = new Object[6];
            dummyRow[0] = patient.getPatientId();
//            dummyRow[1] = patient.getFirstName();
            dummyRow[1] = patient.getVitalSign().getBpLow();
            dummyRow[2] = patient.getVitalSign().getBpHigh();
            dummyRow[3] = patient.getVitalSign().getHeartRate();
            dummyRow[4] = patient.getVitalSign().getWeight();
            TableModelPatient.addRow(dummyRow);
    
    }
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ArrayList<Patient> tempList = new ArrayList<Patient>();
        
        System.out.println("check 9");
        if(searchComboBox.getSelectedItem().toString() == "ID"){
            System.out.println("check 10");
            int idSearch = Integer.parseInt(txtSearchLow.getText());
            
            for(Patient patient : patientList.getPatientList()){
                if(patient.getPatientId() == idSearch){
                    tempList.add(patient);
                }
            }
            
            DisplayPatientData(tempList);
            
        }
        
        if(searchComboBox.getSelectedItem().toString() == "Community"){
            System.out.println("check 11");
            String community = txtSearchLow.getText();
            
            for(Patient patient : patientList.getPatientList()){
                if(patient.getHomeAddress().getCommunity().equals(community)){
                    System.out.println(patient.getHomeAddress().getCommunity());
                    tempList.add(patient);
                }
            }
            
            DisplayPatientData(tempList);
        
        }
        
        if(searchComboBox.getSelectedItem().toString() == "City"){
            System.out.println("check 12");
            String city = txtSearchLow.getText();
            
            for(Patient patient : patientList.getPatientList()){
                System.out.println(patient.getHomeAddress().getCity());
                System.out.println(city);
                if(patient.getHomeAddress().getCity().equals(city)){
                    System.out.println(patient.getHomeAddress().getCity());
                    
                    tempList.add(patient);
                }
            }
            
            DisplayPatientData(tempList);
            
        }
        
        if(searchComboBox.getSelectedItem().toString() == "Age"){
            System.out.println("check 9");
            int low = Integer.parseInt(txtSearchLow.getText());
            int high = Integer.parseInt(txtSearchHigh.getText());
            
            for(Patient patient : patientList.getPatientList()){
                if(patient.getAge() >= low && patient.getAge() < high){
                    tempList.add(patient);
                }
            }
            
            DisplayPatientData(tempList);
        
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void searchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboBoxActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchComboBoxActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JTable tableEncounter;
    private javax.swing.JTable tablePatientRecord;
    private javax.swing.JTextField txtSearchHigh;
    private javax.swing.JTextField txtSearchLow;
    // End of variables declaration//GEN-END:variables
}
